name: tokenizer
description: Mostafa Fahimi base project which contains tools for starting a new project
version: 0.0.7

environment:
  sdk: ">=2.13.4 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0+2

dev_dependencies:
  lint: ^1.6.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: wyekan
      fonts:
        - asset: assets/fonts/w_yekan_bold.ttf
          weight: 700
        - asset: assets/fonts/w_yekan.ttf
          weight: 400
